
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author 
 * Donatus Ankah Edzebubu
 */
public class calculator extends javax.swing.JFrame {
DefaultListModel addgrade =new DefaultListModel();
DefaultListModel addhrs =new DefaultListModel();
DecimalFormat fmt = new DecimalFormat("0.00");
double gradecount;
double counthrs;
    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
         btncalculate.setVisible(false);
         btnOK.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtgrade = new javax.swing.JTextField();
        jtxthours = new javax.swing.JTextField();
        jbtnadd = new javax.swing.JButton();
        btncalculate = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        label = new javax.swing.JLabel();
        lblgpa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("03160329");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter Grade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Credit Hours:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jtxtgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtgradeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 30));
        getContentPane().add(jtxthours, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 140, 30));

        jbtnadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnadd.setText("Add");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 81, 37));

        btncalculate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncalculate.setText("Calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btncalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 89, 37));

        jbtnreset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 80, 37));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 0, 0));

        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jList2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 0, 10));

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("GPA");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 50, -1));

        lblgpa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblgpa.setText("Class Achieved");
        getContentPane().add(lblgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 140, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel3.setText("GPA CALCULATOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 320, 50));

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 50, 30));

        jMenu1.setText("About");

        jMenuItem3.setText("Info");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtgradeActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
 
        btnOK.setVisible(true);
        String a = jtxtgrade.getText();
    String hr = jtxthours.getText();
    double hrs =Double.parseDouble(jtxthours.getText());
    
  if(a.equals("A+") || a.equals("B")|| a.equals("B+")|| a.equals("A")
          || a.equals("C+") || a.equals("C")|| a.equals("D+")|| a.equals("D")
          || a.equals("F") && (hrs >0 || hrs <20)){
    try{
        switch (a) {
            case "A+":
                addgrade.addElement(String.valueOf(5.0*hrs));
                addhrs.addElement(hr);
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+5.0*hrs;
                counthrs=counthrs + hrs;
                break;
            case "A":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(4.5*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+4.5*hrs;
                counthrs=counthrs+hrs;
                break;
            case "B+":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(4.0*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+4.0*hrs;
                counthrs=counthrs+hrs;
                break;
            case "B":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(3.5*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+3.5*hrs;
                counthrs=counthrs+hrs;
                break;
            case "C+":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(3.0*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+3.0*hrs;
                counthrs=counthrs+hrs;
                break;
            case "C":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(2.5*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+2.5*hrs;
                counthrs=counthrs+hrs;
                break;
            case "D+":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(2.0*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+2.0*hrs;
                counthrs=counthrs+hrs;
                break;
            case "D":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(1.5*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+1.5*hrs;
                counthrs=counthrs+hrs;
                break;
            case "F":
                addhrs.addElement(hr);
                addgrade.addElement(String.valueOf(0.0*hrs));
                jList1.setModel(addgrade);
                jList2.setModel(addhrs);
                gradecount=gradecount+0.0*hrs;
                counthrs=counthrs+hrs;
                break;
            default:
                break;
        }
      }catch(Exception e){
        JOptionPane.showMessageDialog(null, "INVALID INPUT FOR GRADE OR CREDIT HOURS","error", JOptionPane.ERROR_MESSAGE);
      }
     jtxtgrade.setText(null);
      jtxthours.setText(null);
         } else{ 
      
     JOptionPane.showMessageDialog(null, "INVALID INPUT FOR GRADE OR CREDIT HOURS","error", JOptionPane.ERROR_MESSAGE);
            
  }
      
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       jList1.setVisible(true);
        jList2.setVisible(false);
    
        gradecount=0.0;
        counthrs=0.0;
    }//GEN-LAST:event_formWindowActivated

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
       double ans = gradecount/counthrs;
       label.setText(""+fmt.format(ans));
    if(ans>=4.0 && ans<=5.0){
        lblgpa.setText("First Class");
       }
         
         else if(ans>=3.0 && ans<=3.99){
        lblgpa.setText("Second Class Upper");
       }
         else if(ans>=2.0 && ans<=2.99){
        lblgpa.setText("Second Class Lower");
       }
        
          else if(ans>=1.0 && ans<=1.99){
        lblgpa.setText("Pass");
       }
          
          else if(ans>=0.0 && ans<=0.99){
        lblgpa.setText("Attempted HND");
       }
          
        jtxtgrade.setText(null);
      jtxthours.setText(null);
      
      
    }//GEN-LAST:event_btncalculateActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
      btnOK.setVisible(false);
      btncalculate.setVisible(false);
      jtxtgrade.setText(null);
      jtxthours.setText(null);
      label.setText("GPA");
      addgrade.clear();
      addhrs.clear();
     gradecount=0.0;
      counthrs=0.0;
      lblgpa.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
      
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
           JOptionPane.showMessageDialog(null, "Ankah Donatus Edzebubu Kofi\n03160329\nHND Computer Science 3","info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jList2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2KeyTyped

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        btncalculate.setVisible(true);
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btncalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JTextField jtxtgrade;
    private javax.swing.JTextField jtxthours;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblgpa;
    // End of variables declaration//GEN-END:variables
}
